### ISSUE TITLE
Too many binary files are checked in

### ISSUE THREAD

**Issue by arran4** [Brabados/RhysBuszkoGoogleCodeJam#2]
Typically you wouldn't put that many binary files in. It can also leak secrets. Info about your computer, passwords, and other things.. So it's best to remove them.

The easiest way is to never have added them by using a comprehensive git ignore. I just googled this one:
https://gist.github.com/brazilnut2000/8226958

That might be applicable. However when you create a repo in github it offers a suggestion:
![image](https://user-images.githubusercontent.com/111667/136318335-2e700744-9c1b-47e7-94b1-39d32251d0b2.png)

**Comment by Brabados** [comment]
Nah, I was always give a gitignore whioe in university. With your suggestion didn't take long to work it out. The file deleting didn't break anything on my side so we all good.

**Comment by arran4** [comment]
Ah cool.
